version: '3.8'

services:
  jetbrains-ai-proxy:
    build:
      context: ./jetbrains-ai-proxy
      dockerfile: Dockerfile
    container_name: jetbrains-ai-proxy
    ports:
      - "8080:8080"
    environment:
      - JWT_TOKENS=${JWT_TOKENS}
      - BEARER_TOKEN=${BEARER_TOKEN}
      - LOAD_BALANCE_STRATEGY=${LOAD_BALANCE_STRATEGY:-round_robin}
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
    volumes:
      - ./jetbrains-ai-proxy/config:/app/config:ro
      - ./jetbrains-ai-proxy/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 1000s
      timeout: 30s
      retries: 3
      start_period: 40s
